set nocompatible
set backspace=indent,eol,start
set history=50
set ruler
set showcmd
set autoindent

syntax on
set hlsearch

if has("vms")
  set nobackup
else
  set backup
endif

if has("autocmd")
  filetype plugin indent on
  autocmd FileType text setlocal textwidth=78
else
